mybatis:
#  mapperLocations: classpath:mybatis/*-mapper.xml
#  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: com.mud.entity
#  checkConfigLocation: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sanguo?useUnicode=true&characterEncoding=utf-8
    username: sanguo
    password: sanguo
    driver-class-name: com.mysql.jdbc.Driver