mybatis:
#  mapperLocations: classpath:mybatis/*-mapper.xml
#  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: com.mud.entity
#  checkConfigLocation: false

spring:
  datasource:
    url: jdbc:mysql://rm-wz9sw694mi8020vigo.mysql.rds.aliyuncs.com:3306/sanguo?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: A845240287a
    driver-class-name: com.mysql.jdbc.Driver